### Token Create
POST http://localhost:4001/api/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGDS"
}

### Rumah Sakit
GET http://127.0.0.1:4001/api/rumahsakit?nama=jantung
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MTEzNTAzMSwiZXhwIjoxNjgxMTM1NjMxfQ.e26RBBGmkPuRoU45X_0NyakNsLs0DYx-tJD5cAZpyn4

### Klinik
GET http://127.0.0.1:4001/api/klinik/11010300009
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MTE5NTQ2OSwiZXhwIjoxNjgxMTk2MDY5fQ.bA8gBF37ahelcFzIaXyzug35curMtR69r5r57q10Wl4

### Klinik Specific
GET http://127.0.0.1:4001/api/klinik/1211178
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY2MzIwNTI0NiwiZXhwIjoxNjYzMjA1ODQ2fQ.an5d7bCRF8DWWWOBilLQNyudYED27GALNucO5_S8Nn8

### Praktek Mandiri
http://localhost:4001/api/praktekmandiri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJfbmFtZSI6ImR0b3NhdHVzZWhhdEBrZW1rZXMuZ28uaWQiLCJpYXQiOjE2ODE0MzY2MzksImV4cCI6MTY4MTQzNzIzOX0.OuvGsRecSGo1Ac4GSFJZAIyXjTO5lXo5OMM1UiEnJA0

### Praktek Mandiri Specific
http://127.0.0.1:4001/api/praktekmandiri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTM3OCwiZXhwIjoxNjc4NTc1OTc4fQ.GpSO3O90sb6eDQte9ZkELX-tupFo3QASjB6MS_7wm8M

### LabKes
GET http://127.0.0.1:4001/api/labkes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTM3OCwiZXhwIjoxNjc4NTc1OTc4fQ.GpSO3O90sb6eDQte9ZkELX-tupFo3QASjB6MS_7wm8M

### LabKes Specific
GET http://127.0.0.1:4001/api/labkes/1610111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU

### UTD
GET http://127.0.0.1:4001/api/utd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTA1OTU1NSwiZXhwIjoxNjc5MDYwMTU1fQ.ds_ST42yAQiBM0k7h59eNK3G73UNjS_bXnxbti7zWJA

### UTD Specific
GET http://127.0.0.1:4001/api/utd/1510015
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU

### Login
POST http://202.70.136.86/reviewtpmd/v1/login 
Content-Type: application/json

{
    "email": "dtosatusehat@kemkes.go.id",
    "password": "DTOs4TS3t!!!"
}



###
GET http://202.70.136.86/reviewtpmd/v1/nakes/31740100001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6ImFsZWsiLCJlbWFpbCI6ImR0b3NhdHVzZWhhdEBrZW1rZXMuZ28uaWQiLCJpYXQiOjE2ODE0Mzc3NjQsImV4cCI6MTY4MTQzODY2NH0.8beCDPMTcLZyoT4I1bG826Gdgg32O7zjBJLyP5KNUAg