### Token Create
POST http://127.0.0.1:4001/api/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### Rumah Sakit
GET http://127.0.0.1:4001/api/rumahsakit?nama=dharmais
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NjIwNywiZXhwIjoxNjc4NTc2ODA3fQ.4PxoeADhF1HocavkAskAPoP-9J9UfC9YoZ3MvbOUoSg

### Klinik
GET http://127.0.0.1:4001/api/klinik?nama=fdfdfd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTM3OCwiZXhwIjoxNjc4NTc1OTc4fQ.GpSO3O90sb6eDQte9ZkELX-tupFo3QASjB6MS_7wm8M

### Klinik Specific
GET http://127.0.0.1:4001/api/klinik/1211178
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY2MzIwNTI0NiwiZXhwIjoxNjYzMjA1ODQ2fQ.an5d7bCRF8DWWWOBilLQNyudYED27GALNucO5_S8Nn8

### Praktek Mandiri
http://127.0.0.1:4001/api/praktekmandiri?nama=rezifa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTM3OCwiZXhwIjoxNjc4NTc1OTc4fQ.GpSO3O90sb6eDQte9ZkELX-tupFo3QASjB6MS_7wm8M

### Praktek Mandiri Specific
http://127.0.0.1:4001/api/praktekmandiri/12020100001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTM3OCwiZXhwIjoxNjc4NTc1OTc4fQ.GpSO3O90sb6eDQte9ZkELX-tupFo3QASjB6MS_7wm8M

### LabKes
GET http://127.0.0.1:4001/api/labkes?nama=fdfdfd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU

### LabKes Specific
GET http://127.0.0.1:4001/api/labkes/1610111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU

### UTD
GET http://127.0.0.1:4001/api/utd?nama=tfdfd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU

### UTD Specific
GET http://127.0.0.1:4001/api/utd/1510015
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY3ODU3NTk4NCwiZXhwIjoxNjc4NTc2NTg0fQ.Lck10VADzA6Iuw8YWMvVNtsuY6_xzm7KAhfgl4O8pvU